"""categories problems problem_reports

Revision ID: d11c43303a9f
Revises: 
Create Date: 2026-10-03 18:49:56.707696

"""
from alembic import op
import sqlalchemy as sa


revision = 'd11c43303a9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=64), server_default='circle-alert', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_importance_level_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending', 'rejected', name='categorystatus', native_enum=False, length=16), server_default='approved', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_status'), 'categories', ['status'], unique=False)
    op.create_table('problems',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'resolved', 'rejected', name='problemstatus', native_enum=False, length=16), server_default='new', nullable=False),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.Column('is_observable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reports_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirmations_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('denials_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consecutive_denials', sa.Integer(), server_default='0', nullable=False),
    sa.Column('importance_level_average', sa.Float(), nullable=True),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_category_id'), 'problems', ['category_id'], unique=False)
    op.create_index(op.f('ix_problems_confirmations_count'), 'problems', ['confirmations_count'], unique=False)
    op.create_index(op.f('ix_problems_importance_level_average'), 'problems', ['importance_level_average'], unique=False)
    op.create_index(op.f('ix_problems_is_observable'), 'problems', ['is_observable'], unique=False)
    op.create_index(op.f('ix_problems_last_reported_at'), 'problems', ['last_reported_at'], unique=False)
    op.create_index('ix_problems_lat_lng', 'problems', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_problems_status'), 'problems', ['status'], unique=False)
    op.create_table('problem_reports',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('is_observable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('importance_level', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('form', 'voice', 'proximity_prompt', name='reportsource', native_enum=False, length=24), server_default='form', nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('importance_level IS NULL OR importance_level BETWEEN 1 AND 5', name='ck_problem_reports_importance_level_range'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_reports_problem_id'), 'problem_reports', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_reports_reported_at'), 'problem_reports', ['reported_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_reports_reported_at'), table_name='problem_reports')
    op.drop_index(op.f('ix_problem_reports_problem_id'), table_name='problem_reports')
    op.drop_table('problem_reports')
    op.drop_index(op.f('ix_problems_status'), table_name='problems')
    op.drop_index('ix_problems_lat_lng', table_name='problems')
    op.drop_index(op.f('ix_problems_last_reported_at'), table_name='problems')
    op.drop_index(op.f('ix_problems_is_observable'), table_name='problems')
    op.drop_index(op.f('ix_problems_importance_level_average'), table_name='problems')
    op.drop_index(op.f('ix_problems_confirmations_count'), table_name='problems')
    op.drop_index(op.f('ix_problems_category_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_categories_status'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
